---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::pandas=2.2.3
  - conda-forge::pip=25.0.1
  - conda-forge::python=3.11.11
  - pip:
      - metaspace2020==2.0.9
