# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "metaspace_download"
description: A module to download dataset results from the METASPACE platform and save them as CSV files, using a containerized Python script. Inputs are provided via a CSV file or a list of datasets, with results saved to a specified output directory.
keywords:
  - metaspace
  - metabolite annotation
  - data-download
  - csv
  - metabolomics
tools:
  - metaspace:
      description: METASPACE is a platform for metabolite annotation of imaging mass spectrometry data.
      homepage: https://metaspace2020.eu/
      documentation: https://metaspace2020.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/metaspace2020/metaspace
      doi: 10.1038/nmeth.4072
      licence: ["MIT License"]
      identifier: biotools:metaspace

input:
  - - container:
        type: string
        description: |
          Docker container image used to run the download process (default: 'bwadie/metaspace_converter').
        optional: false
    - output:
        type: string
        description: |
          Directory where the downloaded CSV results will be saved (default: 'results').
        optional: false
    - input_csv:
        type: string
        description: |
          Path to a CSV file containing dataset details (default: false).
          If provided, must contain columns: dataset_id, database, version.
          If no database or version is specified, just leave it blank.
          Example:
            dataset_id,database,version
            2022-08-05_17h28m56s,KEGG,
            2022-08-05_17h28m56s,GNPS,
            2023-01-01_12h34m56s,,
          Either this or datasets must be specified.
        optional: true
    - datasets:
        type: list
        description: |
          List of dataset details (default: false).
          Each item is a list of [dataset_id, database (optional), version (optional)].
          Either this or input_csv must be specified.
        optional: true

output:
  - results:
      - "*.csv":
          type: file
          description: |
            CSV file containing the downloaded dataset results, saved to the directory specified by the output parameter.
            Filename format is '{dataset_id}_*.csv'.
          pattern: "*.csv"
          ontologies:
            - edam: "http://edamontology.org/format_3752" # CSV format
  - log:
      - stdout:
          type: string
          description: The standard output (stdout) of the script, containing log messages.

authors:
  - "@Dewey-Wang"
maintainers:
  - "@Dewey-Wang"
